### ISSUE TITLE
with version 1.0.3 TASK [libvirt : set image_src for uncompressed files] fails

### ISSUE THREAD

**Issue by bhavikbhavsar** [CentOS-PaaS-SIG/linchpin#364]
This was working fine with 1.0.2 

Steps to reproduce:
1. pip2 install linchpin
2. utilized the same example.topology.yml and example-layout.yml
3. linchpin -v up

TASK [libvirt : set image_src for uncompressed files] ****************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'lismt.stat.mime_type == \"application/octet-stream\"' failed. The error was: error while evaluating conditional (lismt.stat.mime_type == \"application/octet-stream\"): 'dict object' has no attribute 'mime_type'\n\nThe error appears to have been in '/usr/lib/python2.7/site-packages/linchpin/provision/roles/libvirt/tasks/copy_image_src.yml': line 44, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"set image_src for uncompressed files\"\n  ^ here\n"}

if you again downgrade to 1.0.2 it works

**Comment by herlo** [comment]
Are you using a virtualenv? Did you symlink the libselinux-python libraries?

```
$ sudo dnf install libvirt-devel libselinux-python
$ ln -s ${LIBSELINUX_PATH}/selinux ${VIRTUAL_ENV}/${VENV_LIB_PATH} &> /dev/null
$ ln -s ${LIBSELINUX_PATH}/_selinux.so ${VIRTUAL_ENV}/${VENV_LIB_PATH} &> /dev/null
```
If so, I'm happy to look into this further.

**Comment by herlo** [comment]
Ok, it looks like ansible 2.3 changed the internal structure of the returned stat object slightly. Instead of `mime_type` it's now `mimetype`. I've updated the code for Ansible 2.3.1+ going forward. Watch for a Pull Request later today.
