### ISSUE TITLE
Linchpin journal does not work in 1.7.4

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#1120]
**Describe the bug**
linchpin journal does not work in 1.7.4
**To Reproduce**
```
[root@hpe-xl450gen10-01 linchpin_workspace]# pip install linchpin
[root@hpe-xl450gen10-01 linchpin_workspace]# linchpin --workspace . journal
Traceback (most recent call last):
  File "/usr/bin/linchpin", line 11, in <module>
    sys.exit(runcli())
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/linchpin/shell/__init__.py", line 487, in journal
    all_fields = list(json.loads(lpcli_cfg.keys()))
AttributeError: 'unicode' object has no attribute 'keys'
[root@hpe-xl450gen10-01 linchpin_workspace]# pip uninstall linchpin
Uninstalling linchpin-1.7.4:
  Would remove:
    /usr/bin/install_libvirt_deps.sh
    /usr/bin/install_selinux_venv.sh
    /usr/bin/linchpin
    /usr/lib/python2.7/site-packages/linchpin-1.7.4.dist-info/*
    /usr/lib/python2.7/site-packages/linchpin/*
Proceed (y/n)? y
  Successfully uninstalled linchpin-1.7.4
[root@hpe-xl450gen10-01 linchpin_workspace]# pip install linchpin==1.7.3
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting linchpin==1.7.3
  Downloading https://files.pythonhosted.org/packages/ce/5a/152bc088eeb1b0d12696688aba2134e26320a3d38e20a479a726aab00fc3/linchpin-1.7.3-py2-none-any.whl (303kB)
    100% |████████████████████████████████| 307kB 40.1MB/s 
Requirement already satisfied: configparser>=3.5.0 in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (3.7.4)
Requirement already satisfied: openshift>=0.6 in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (0.8.8)
Requirement already satisfied: setuptools>=35.0 in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (40.8.0)
Requirement already satisfied: requests>=2.21.0 in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (2.21.0)
Requirement already satisfied: ipaddress>=1.0.17 in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (1.0.18)
Collecting pycrypto>=2.6.1 (from linchpin==1.7.3)
  Downloading https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 450kB 43.5MB/s 
Requirement already satisfied: shade>=1.30.0 in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (1.31.0)
Requirement already satisfied: naked in /usr/lib64/python2.7/site-packages (from linchpin==1.7.3) (0.1.31)
Requirement already satisfied: pyasn1>=0.1.9 in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (0.4.5)
Requirement already satisfied: Cerberus>=1.2 in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (1.3)
Requirement already satisfied: pyopenssl in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (19.0.0)
Requirement already satisfied: ansible>=2.7.1 in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (2.7.10)
Requirement already satisfied: yamlordereddictloader in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (0.4.0)
Requirement already satisfied: click in /usr/lib64/python2.7/site-packages (from linchpin==1.7.3) (7.0)
Requirement already satisfied: jinja2>=2.10 in /usr/lib64/python2.7/site-packages (from linchpin==1.7.3) (2.10.1)
Requirement already satisfied: tinydb in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (3.13.0)
Requirement already satisfied: boto3 in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (1.9.138)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (1.11.0)
Requirement already satisfied: apache-libcloud>=0.20.1 in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (2.4.0)
Requirement already satisfied: PyYAML>=3.12 in /usr/lib64/python2.7/site-packages (from linchpin==1.7.3) (5.1)
Requirement already satisfied: boto>=2.49.0 in /usr/lib/python2.7/site-packages (from linchpin==1.7.3) (2.49.0)
Requirement already satisfied: dictdiffer in /usr/lib/python2.7/site-packages (from openshift>=0.6->linchpin==1.7.3) (0.8.0)
Requirement already satisfied: kubernetes<9.0.0,>=8.0.0 in /usr/lib/python2.7/site-packages (from openshift>=0.6->linchpin==1.7.3) (8.0.1)
Requirement already satisfied: urllib3<1.25 in /usr/lib/python2.7/site-packages (from openshift>=0.6->linchpin==1.7.3) (1.24.2)
Requirement already satisfied: python-string-utils in /usr/lib/python2.7/site-packages (from openshift>=0.6->linchpin==1.7.3) (0.6.0)
Requirement already satisfied: ruamel.yaml>=0.15 in /usr/lib64/python2.7/site-packages (from openshift>=0.6->linchpin==1.7.3) (0.15.94)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests>=2.21.0->linchpin==1.7.3) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python2.7/site-packages (from requests>=2.21.0->linchpin==1.7.3) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests>=2.21.0->linchpin==1.7.3) (2019.3.9)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /usr/lib/python2.7/site-packages (from shade>=1.30.0->linchpin==1.7.3) (5.2.0)
Requirement already satisfied: openstacksdk>=0.15.0 in /usr/lib/python2.7/site-packages (from shade>=1.30.0->linchpin==1.7.3) (0.27.0)
Requirement already satisfied: os-client-config>=1.28.0 in /usr/lib/python2.7/site-packages (from shade>=1.30.0->linchpin==1.7.3) (1.32.0)
Requirement already satisfied: cryptography>=2.3 in /usr/lib64/python2.7/site-packages (from pyopenssl->linchpin==1.7.3) (2.3)
Requirement already satisfied: paramiko in /usr/lib/python2.7/site-packages (from ansible>=2.7.1->linchpin==1.7.3) (2.4.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib64/python2.7/site-packages (from jinja2>=2.10->linchpin==1.7.3) (1.1.1)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/lib/python2.7/site-packages (from boto3->linchpin==1.7.3) (0.9.4)
Requirement already satisfied: botocore<1.13.0,>=1.12.138 in /usr/lib/python2.7/site-packages (from boto3->linchpin==1.7.3) (1.12.138)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in /usr/lib/python2.7/site-packages (from boto3->linchpin==1.7.3) (0.2.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/lib/python2.7/site-packages (from kubernetes<9.0.0,>=8.0.0->openshift>=0.6->linchpin==1.7.3) (0.56.0)
Requirement already satisfied: requests-oauthlib in /usr/lib/python2.7/site-packages (from kubernetes<9.0.0,>=8.0.0->openshift>=0.6->linchpin==1.7.3) (1.2.0)
Requirement already satisfied: adal>=1.0.2 in /usr/lib/python2.7/site-packages (from kubernetes<9.0.0,>=8.0.0->openshift>=0.6->linchpin==1.7.3) (1.2.1)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/lib/python2.7/site-packages (from kubernetes<9.0.0,>=8.0.0->openshift>=0.6->linchpin==1.7.3) (2.8.0)
Requirement already satisfied: google-auth>=1.0.1 in /usr/lib/python2.7/site-packages (from kubernetes<9.0.0,>=8.0.0->openshift>=0.6->linchpin==1.7.3) (1.6.3)
Requirement already satisfied: ruamel.ordereddict; platform_python_implementation == "CPython" and python_version <= "2.7" in /usr/lib64/python2.7/site-packages (from ruamel.yaml>=0.15->openshift>=0.6->linchpin==1.7.3) (0.4.13)
Requirement already satisfied: dogpile.cache>=0.6.2 in /usr/lib/python2.7/site-packages (from openstacksdk>=0.15.0->shade>=1.30.0->linchpin==1.7.3) (0.7.1)
Requirement already satisfied: decorator>=3.4.0 in /usr/lib/python2.7/site-packages (from openstacksdk>=0.15.0->shade>=1.30.0->linchpin==1.7.3) (4.4.0)
Requirement already satisfied: iso8601>=0.1.11 in /usr/lib/python2.7/site-packages (from openstacksdk>=0.15.0->shade>=1.30.0->linchpin==1.7.3) (0.1.12)
Requirement already satisfied: os-service-types>=1.2.0 in /usr/lib/python2.7/site-packages (from openstacksdk>=0.15.0->shade>=1.30.0->linchpin==1.7.3) (1.6.0)
Requirement already satisfied: netifaces>=0.10.4 in /usr/lib64/python2.7/site-packages (from openstacksdk>=0.15.0->shade>=1.30.0->linchpin==1.7.3) (0.10.9)
Requirement already satisfied: requestsexceptions>=1.2.0 in /usr/lib/python2.7/site-packages (from openstacksdk>=0.15.0->shade>=1.30.0->linchpin==1.7.3) (1.4.0)
Requirement already satisfied: keystoneauth1>=3.13.0 in /usr/lib/python2.7/site-packages (from openstacksdk>=0.15.0->shade>=1.30.0->linchpin==1.7.3) (3.14.0)
Requirement already satisfied: munch>=2.1.0 in /usr/lib/python2.7/site-packages (from openstacksdk>=0.15.0->shade>=1.30.0->linchpin==1.7.3) (2.3.2)
Requirement already satisfied: futures>=3.0.0; python_version == "2.7" or python_version == "2.6" in /usr/lib/python2.7/site-packages (from openstacksdk>=0.15.0->shade>=1.30.0->linchpin==1.7.3) (3.2.0)
Requirement already satisfied: appdirs>=1.3.0 in /usr/lib/python2.7/site-packages (from openstacksdk>=0.15.0->shade>=1.30.0->linchpin==1.7.3) (1.4.3)
Requirement already satisfied: jsonpatch!=1.20,>=1.16 in /usr/lib/python2.7/site-packages (from openstacksdk>=0.15.0->shade>=1.30.0->linchpin==1.7.3) (1.23)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography>=2.3->pyopenssl->linchpin==1.7.3) (0.24.0)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /usr/lib64/python2.7/site-packages (from cryptography>=2.3->pyopenssl->linchpin==1.7.3) (1.11.5)
Requirement already satisfied: enum34 in /usr/lib/python2.7/site-packages (from cryptography>=2.3->pyopenssl->linchpin==1.7.3) (1.1.6)
Requirement already satisfied: pynacl>=1.0.1 in /usr/lib64/python2.7/site-packages (from paramiko->ansible>=2.7.1->linchpin==1.7.3) (1.3.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/lib64/python2.7/site-packages (from paramiko->ansible>=2.7.1->linchpin==1.7.3) (3.1.6)
Requirement already satisfied: docutils>=0.10 in /usr/lib/python2.7/site-packages (from botocore<1.13.0,>=1.12.138->boto3->linchpin==1.7.3) (0.14)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python2.7/site-packages (from requests-oauthlib->kubernetes<9.0.0,>=8.0.0->openshift>=0.6->linchpin==1.7.3) (3.0.1)
Requirement already satisfied: PyJWT>=1.0.0 in /usr/lib/python2.7/site-packages (from adal>=1.0.2->kubernetes<9.0.0,>=8.0.0->openshift>=0.6->linchpin==1.7.3) (1.7.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/lib/python2.7/site-packages (from google-auth>=1.0.1->kubernetes<9.0.0,>=8.0.0->openshift>=0.6->linchpin==1.7.3) (0.2.5)
Requirement already satisfied: cachetools>=2.0.0 in /usr/lib/python2.7/site-packages (from google-auth>=1.0.1->kubernetes<9.0.0,>=8.0.0->openshift>=0.6->linchpin==1.7.3) (3.1.0)
Requirement already satisfied: rsa>=3.1.4 in /usr/lib/python2.7/site-packages (from google-auth>=1.0.1->kubernetes<9.0.0,>=8.0.0->openshift>=0.6->linchpin==1.7.3) (4.0)
Requirement already satisfied: stevedore>=1.20.0 in /usr/lib/python2.7/site-packages (from keystoneauth1>=3.13.0->openstacksdk>=0.15.0->shade>=1.30.0->linchpin==1.7.3) (1.30.1)
Requirement already satisfied: jsonpointer>=1.9 in /usr/lib/python2.7/site-packages (from jsonpatch!=1.20,>=1.16->openstacksdk>=0.15.0->shade>=1.30.0->linchpin==1.7.3) (2.0)
Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.7->cryptography>=2.3->pyopenssl->linchpin==1.7.3) (2.14)
Installing collected packages: pycrypto, linchpin
  Running setup.py install for pycrypto ... done
Successfully installed linchpin-1.7.3 pycrypto-2.6.1
[root@hpe-xl450gen10-01 linchpin_workspace]# linchpin --workspace . journal

Target: beaker-bm
run_id	    action	     uhash	        rc	
--------------------------------------------------
1      	       up	   3f6659	        0	


run_id	    action	     uhash	        rc	
--------------------------------------------------
[root@hpe-xl450gen10-01 linchpin_workspace]#
```
