### ISSUE TITLE
ImportError post linchpin upgrade to 1.0.3

### ISSUE THREAD

**Issue by gsr-shanks** [CentOS-PaaS-SIG/linchpin#370]
Post linchpin upgrade I see the following:

```
$ linchpin -h
Traceback (most recent call last):
  File "/usr/bin/linchpin", line 7, in <module>
    from linchpin import runcli
  File "/usr/lib/python2.7/site-packages/linchpin/__init__.py", line 7, in <module>
    from linchpin.cli import LinchpinCli
  File "/usr/lib/python2.7/site-packages/linchpin/cli/__init__.py", line 8, in <module>
    from linchpin.api import LinchpinAPI
  File "/usr/lib/python2.7/site-packages/linchpin/api/__init__.py", line 11, in <module>
    from ansible.inventory import Inventory
ImportError: cannot import name Inventory
```

```
$ ansible --version
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/home/fedora/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

```
$ cat /etc/redhat-release 
Fedora release 26 (Twenty Six)
```

**Comment by gsr-shanks** [comment]
Import works with ansible 2.3.1.0

```
# ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]


# python
Python 2.7.5 (default, Oct 11 2015, 17:47:16) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ansible.inventory import Inventory
>>> 
```

**Comment by herlo** [comment]
This has been fixed in #369. If you would rather not use ansible 2.3.x, please update your code to this point in the git tree at a minimum.

**Comment by gsr-shanks** [comment]
When is this expected to land in pip ? Any ETA ?

**Comment by herlo** [comment]
It's already there. https://pypi.python.org/pypi/linchpin

You may need to perform an upgrade if you already have 1.0.2 installed.

**Comment by greg-hellings** [comment]
@herlo Per the subject heading, the bug affects 1.0.3, which is still the latest version on PyPI. I believe @gsr-shanks was wondering when a 1.0.4 will be cut to include the fix for this (also relevant to Cinch, as Beaker is broken in 1.0.3 and awaiting a fix).

**Comment by herlo** [comment]
Ah good point. Let me look into it and see if I can cut something today.

**Comment by herlo** [comment]
1.0.4 was cut on Friday, and is up on PyPI.

**Comment by gsr-shanks** [comment]
Thank you
